### ISSUE TITLE
Game crash in the editor mode

### ISSUE THREAD

**Issue by Roki110** [redcrab2016/Captain-Lander#2]
### In the console

> Traceback (most recent call last):
  File "D:\Game\Misc\Captain-Lander-master\lander.py", line 1801, in <module>
    RedcrabLander().play()
  File "D:\Game\Misc\Captain-Lander-master\lander.py", line 1794, in play
    self.run = self.game.tick(self.game_context)
  File "D:\Game\Misc\Captain-Lander-master\lander.py", line 984, in tick
    self.scene.ground[i] = self.scene.ground[i - 1]
IndexError: list assignment index out of range

**Comment by redcrab2016** [comment]
Thanks for the report, issue is fixed
